"""empty message

Revision ID: 701fe692bfd2
Revises: fa277e42579e
Create Date: 2019-05-08 13:33:11.939996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701fe692bfd2'
down_revision = 'fa277e42579e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_idcard', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('is_save', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_save')
    op.drop_column('orders', 'is_idcard')
    # ### end Alembic commands ###
