"""empty message

Revision ID: be65832327d5
Revises: 10bb70e1e578
Create Date: 2019-03-28 14:57:38.573507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be65832327d5'
down_revision = '10bb70e1e578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'qrcode')
    op.add_column('orders', sa.Column('qrcode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'qrcode')
    op.add_column('files', sa.Column('qrcode', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
