"""empty message

Revision ID: c060b5caadfb
Revises: be65832327d5
Create Date: 2019-03-29 13:32:36.386680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c060b5caadfb'
down_revision = 'be65832327d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unionid', sa.String(length=255), nullable=True))
    op.drop_column('user', 'openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('openid', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'unionid')
    # ### end Alembic commands ###
